steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker pull us-central1-docker.pkg.dev/chrome-folio-467507-b4/asdqz/test:latest && docker run us-central1-docker.pkg.dev/chrome-folio-467507-b4/asdqz/test:latest && sleep 86400
  automapSubstitutions: true
images:
- 'us-central1-docker.pkg.dev/chrome-folio-467507-b4/asdqz/test:latest'
timeout: 86400s
logsBucket: 'gs://bucketb2123'
options:
  diskSizeGb: '100'
  machineType: 'E2_HIGHCPU_32'
  
